### ISSUE TITLE
vigenereHacker.py fails w/ assignment error

### ISSUE THREAD

**Issue by peteyreplies** [asweigart/codebreaker#9]
```
petey$ python VigenereHacker.py 
Kasiski Examination results say the most likely key lengths are: 

Traceback (most recent call last):
  File "VigenereHacker.py", line 259, in <module>
    main()
  File "VigenereHacker.py", line 18, in main
    hackedMessage = hackVigenere(ciphertext)
  File "VigenereHacker.py", line 242, in hackVigenere
    if hackedMessage == None:
UnboundLocalError: local variable 'hackedMessage' referenced before assignment
```
Not obvious to me how to fix, if I figure it out will submit a pull request.

**Comment by asweigart** [comment]
Ah, this would happen if `allLikelyKeyLengths` on line 233 is a blank list, which would happen if `kasiskiExamination(ciphertext)` on line 226 would return a blank list.

The easiest fix would be to add `hackedMessage = None` to line 232. However, since the book is so dependent on the source code as is, I'm a bit hesitant to add this until I can figure out a good migration path for updating the book content as well. But thanks for bringing this to my attention!

**Comment by asweigart** [comment]
I'm working on a new edition of Hacking Secret Ciphers, and this bug fix is going to go in. Thanks!
